### ISSUE TITLE
Bourbon's linear-gradient doesn't work with libsass (getting null values)

### ISSUE THREAD

**Issue by donaldallen** [bdkjones/CodeKit2#164]
When I have libsass enabled for my project, anything that uses @include linear-gradient(); from Bourbon doesn't work as expected.

Here's the outputted CSS in Chrome with libsass enabled:

![screenshot 2014-01-15 14 25 55](https://f.cloud.github.com/assets/453784/1925508/48fba7fa-7e33-11e3-95c5-365d9179dc0f.png)

And here it is without:

![screenshot 2014-01-15 14 26 24](https://f.cloud.github.com/assets/453784/1925514/4f65c8aa-7e33-11e3-86c4-a145ed58d5cc.png)

And here's the SCSS:

``` css
@include linear-gradient(-45deg, transparent 10px, $highlight 10px, $highlight 100%);
```

And here's the CSS output with libsass enabled:

``` css
  a.btn.blue {
    background-color: transparent;
    background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, transparent 10px), color-stop(11.11111%, #0e6185 10px), color-stop(22.22222%, #0e6185 100%), color-stop(33.33333%, false), color-stop(44.44444%, false), color-stop(55.55556%, false), color-stop(66.66667%, false), color-stop(77.77778%, false), color-stop(88.88889%, false), color-stop(100%, false));
    background-image: -webkit-linear-gradient(-225deg, transparent 10px, #0e6185 10px, #0e6185 100%, false, false, false, false, false, false, false);
    background-image: linear-gradient(-45deg,transparent 10px, #0e6185 10px, #0e6185 100%, false, false, false, false, false, false, false); }
```

And here's the CSS output without libsass:

``` css
  a.btn.blue {
    background-color: transparent;
    background-image: -webkit-gradient(linear, left top, left bottom, color-stop(10px, transparent), color-stop(10px, #0e6185), color-stop(100%, #0e6185));
    background-image: -webkit-linear-gradient(-225deg, transparent 10px, #0e6185 10px, #0e6185 100%);
    background-image: linear-gradient(-45deg,transparent 10px, #0e6185 10px, #0e6185 100%); }
```

There is an issue on libsass that claims this was fixed:

https://github.com/thoughtbot/bourbon/issues/241
