### ISSUE TITLE
Feature Request: Respect LESS-variables in CodeKit's import linker

### ISSUE THREAD

**Issue by leitgab** [bdkjones/CodeKit2#340]
If using variables in LESS-files, e.g.:

``` less
@twbs-less-path: "./../../Public/Libraries/Bootstrap/less/";
@site-less-path: "./";

// Core variables and mixins
@import "@{twbs-less-path}variables.less";
@import "@{site-less-path}Variables.less";
```

changes in imported files are not recognized by CodeKit. Using

``` less
// Core variables and mixins
@import "./../../Public/Libraries/Bootstrap/less/variables.less";
@import "./Variables.less";
```

instead does work. Please respect LESS-variables in CodeKit's import linker.
