### ISSUE TITLE
invalid code in SCSS/libsass KO'd CodeKit; CodeKit waved to corner for maintainers help as it went down.

### ISSUE THREAD

**Issue by subhaze** [bdkjones/CodeKit2#618]
``` scss
a {
    font: {
        size: 14px;
        @media (max-width: 767px){
            size: 10px;
        }
    }
}
```

the above code blows CK up when it tries to compile it. Yes... this isn't valid code due to the placement of the `@media`, but Ruby SCSS correctly reports the issue in logs but if using libsass it just shuts CK down.

P.S. You **MUST use tabs**, github has converted that code to spaces.
